---
title: "child"
author: "sl team"
date: "4/26/2020"
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```


### Current means

```{r}
vars <- measures %>% filter(family == fam & !is.na(variable)) %>% pull(variable)
var_labs <- measures %>% filter(family == fam & !is.na(variable)) %>% pull(short.label)
names(var_labs) <- vars

current_means <- df[, c("id", "date", vars)] %>%
 group_by(id)  %>%
 filter(date == max(date)) %>%
 summarise_all( function(x)  mean(x, na.rm = T)) 

current_means %>% 
 kable(caption = "Mean responses in each district (most recent date)", col.names = c("District", "Date", var_labs), digits = 2)

```

### Time trends

```{r}
# New facet label names for supp variable
pd <- position_dodge(0.1) # move them .05 to the left and right

  df %>% 
    
    select(all_of(c("id", "date", vars))) %>%
    reshape2::melt(id.vars= c("id", "date"))  %>% 
    group_by(id, date, variable) %>%
    summarise_all(list(~mean(., na.rm = TRUE), ~sd(., na.rm = TRUE), ~length(.))) %>%
    mutate(se = sd / sqrt(length)) %>%
    
    ggplot(aes(x=date, y=mean)) + 
    geom_errorbar(aes(ymin=mean-1.96*se, ymax=mean+1.96*se), width=.1, position=pd) +
    geom_line(position=pd) +
    geom_point(position=pd) +
    facet_grid(variable ~ id, labeller = labeller(variable = var_labs)) 

 

```

### Map

Showing most recent data available for each district.

```{r, message = FALSE, warning = FALSE}

par(mar=c(0,0,0,0))

df_map <- left_join(shp_df, current_means)  %>% select(-date) %>%
  reshape2::melt(id.vars= c("id", "long", "lat", "order", "hole", "piece", "group"))

ggplot() +
  geom_polygon(data = df_map, 
               aes( x = long, y = lat,  group = group, fill=value), color="white") +
  theme_void() + coord_map() + facet_wrap(~variable, labeller = labeller(variable = var_labs))


```


### Variable definitions

```{r}

measures %>% filter(family == fam) %>% select(short.label, description) %>% kable(caption = "Data definitions", col.names = c("Measure", "Definition"))


```