---
title: "Make SL dashboard"
output:
  rmdformats::html_clean
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(DT)
# remotes::install_github("wzb-ipi/dashdash")
library(dashdash)
library(readstata13)
```


# Gather inputs

```{r}

#my_vars <- openxlsx::read.xlsx("20200426_measures.xlsx") %>%
my_vars <- openxlsx::read.xlsx("measures.xlsx") %>%
  filter(!is.na(variable))

vars_used  <- my_vars %>% filter(!is.na(variable)) %>% pull(variable)
vars_used  <-c("district", "date", vars_used)

DT::datatable(my_vars, caption = "measures dataframe")

# Fudge to get district ids
dist_df1 <- readstata13::read.dta13("C:/Dropbox/Sierra Leone Covid/5_data/data_in/20200430.dta") %>% select(district) %>% mutate(i = 1:n()) %>% rename(id = district)
district_ids <- readstata13::read.dta13("C:/Dropbox/Sierra Leone Covid/5_data/data_in/20200430.dta", convert.factors = FALSE) %>%select(district) %>% mutate(i = 1:n()) %>% left_join(dist_df1) %>% distinct(district, id)


# Fudge to merge: data should arrive combined
my_data1 <- readstata13::read.dta13("C:/Dropbox/Sierra Leone Covid/5_data/data_in/20200430.dta",
                                   convert.factors = FALSE) 
my_data2 <- readstata13::read.dta13("C:/Dropbox/Sierra Leone Covid/5_data/data_in/20200501.dta",
                                   convert.factors = FALSE)


if(!all(vars_used %in% names(my_data1))){
  print(paste("Missing variables:", 
              paste(vars_used[!(vars_used %in% names(my_data1))], collapse = ", ")))
  vars_used <- vars_used[(vars_used %in% names(my_data1))]
  }

my_data <- bind_rows(select(my_data1, c(vars_used)), 
                     select(my_data2, vars_used))  %>%
  left_join(district_ids) %>%
  mutate(date = as.Date(date)) 

my_data <-filter(my_data, date >= as.Date("2020-04-30"))

dim(my_vars)
my_vars <- my_vars %>% filter(variable %in% vars_used) 
dim(my_vars)

DT::datatable(my_data, caption = "data dataframe")

my_args <- read.csv("my_args.csv", stringsAsFactors = FALSE)

```



```{r, message = FALSE, warning = FALSE, include = FALSE}

dashdash::dashdash(
  output_file = "C:/Dropbox/Sierra Leone Covid/6_automated_reports/index.html",
  map_path = "C:/Dropbox/github/sl-dashboard/docs/SL/data/shapefiles",
  my_data = my_data,
  my_vars = my_vars,
  my_args = my_args
)

```


You can then view it: [example.html]("../..")

